### ISSUE TITLE
Value function approximator

### ISSUE THREAD

**Issue by supratikp** [aravindr93/mjrl#11]
Looking at https://github.com/aravindr93/mjrl/blob/master/examples/linear_nn_comparison.py, together with a linear policy an mlp is used as the value function approximator. Is this what was used for the experiments in the paper as well?

**Comment by aravindr93** [comment]
No, in the paper we used a quadratic baseline. The trend of linear training faster than NN policy is consistent across any baseline functional form. MLP baseline leads to more variance reduction and hence faster learning for both MLP policy as well as linear policy, but the relative performance differences between MLP policy and linear policy are approximately the same for both quadratic baseline as well as MLP baseline.
