### ISSUE TITLE
why are the advantages multiplied by 1e-2 in dapg.py?

### ISSUE THREAD

**Issue by henrycharlesworth** [aravindr93/mjrl#26]
On line 69 here: https://github.com/aravindr93/mjrl/blob/master/mjrl/algos/dapg.py you have:

```
all_adv = 1e-2*np.concatenate([advantages/(np.std(advantages) + 1e-8), demo_adv])
```

I'm just curious as to what the rationale behind multiplying by 1e-2 is here? especially as if you don't concatenate the demo paths then you don't scale in this way.

**Comment by aravindr93** [comment]
Sorry for the extreme delay.

I think the original rationale was that demo advantages are set to 1.0, which can be quite large causing numerical instability. The scaling provides some numerical conditioning. Typically advantages for the other trajectories are lower. Thus, scaling is not needed if the demos are not used.

That said, we have left in place for a while and have not tried removing. It is possible that the scaling is no longer required after updates and improvements in other parts of the code.
