### ISSUE TITLE
Pickling of _VariableFunctions not compatible with PyTorch 1.5.0

### ISSUE THREAD

**Issue by chinmay-singh** [aravindr93/mjrl#27]
pickling of _VariableFunctions not compatible with PyTorch 1.5.0
It would thus be useful if the version of PyTorch can be specified in the env.yml
![image](https://user-images.githubusercontent.com/37449309/84589414-fab27100-ae4b-11ea-8b12-c4fab66711a1.png)

**Comment by aravindr93** [comment]
Thanks for bringing this up. It seems like a recent change in pytorch is causing the break. Will pin to a specific version for now and will switch to torch.save in upcoming releases.
